language: java
#d:
#- dmd
#haxe:
#- development
node_js:
- '4'
jdk:
- oraclejdk8

#before_install:
#- if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use oraclejdk8; fi
#- if [ "$TRAVIS_OS_NAME" == 'osx']; then "wget --no-cookies --no-check-certificate --header \"Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie\" http://download.oracle.com/otn-pub/java/jdk/8u66-b17/jdk-8u66-macosx-x64.dmg" && hdiutil mount jdk-8u66-macosx-x64.dmg && sudo installer -pkg /Volumes/JDK\ 8\ Update\ 66/JDK\ 8\ Update\ 66.pkg -target LocalSystem; fi
#- if [ "$TRAVIS_OS_NAME" == "linux" ]; sudo apt-get update -qq; fi
#install:
#- if [ "$TRAVIS_OS_NAME" == "linux" ]; sudo add-apt-repository ppa:ondrej/php -y; fi
#- if [ "$TRAVIS_OS_NAME" == "linux" ]; sudo apt-get -y update; fi
#- if [ "$TRAVIS_OS_NAME" == "linux" ]; sudo apt-get -y install php5.6 php5.6-mbstring; fi
#- mvn clean --settings settings.xml
#- nvm install 4 || true
#- nvm use 4 || true

before_install:
- jdk_switcher use oraclejdk8
- sudo apt-key update
- sudo apt-get update -qq

install:
- sudo add-apt-repository ppa:ondrej/php -y
- sudo apt-get -y update
- sudo apt-get -y install php5.6 php5.6-mbstring
#- sudo apt-get -y install gdc # GDC D compiler
- sudo wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
- sudo apt-get update && sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring && sudo apt-get update
- sudo apt-get -y install dmd-bin
- curl -s -S -O http://haxe.org/website-content/downloads/3.3.0-rc.1/downloads/haxe-3.3.0-rc.1-linux64.tar.gz
- tar xzf haxe-3.3.0-rc.1-linux64.tar.gz
- nvm install 4 || true
- nvm use 4 || true

before_script:
- export HAXE_STD_PATH=$PWD/haxe-3.3.0-rc2/std
- export HAXEPATH=$PWD/haxe-3.3.0-rc2
- export PATH=$HAXEPATH:$PATH
- ls -la $PWD
- ls -la $PWD/haxe-3.3.0-rc2
- which java || true
- java -version || true
- which haxe || true
- haxe -version || true
- which nvm || true
- nvm --version || true
- which node || true
- node --version || true
- php --version || true
- dmd --version || true
- ./gradlew --version

script:
- jdk_switcher use oraclejdk8
- ./gradlew -s -i check install
#- ./gradlew check install
- jdk_switcher use oraclejdk7
- pushd jtransc-main-run/example
- "./run"
- popd
- pushd jtransc-main-run/example-gradle
- ../../gradlew runPlainJs && node build/jtransc-js/program.js
- popd
- pushd jtransc-maven-plugin/example
- mvn package
- node target/jtransc-js/program.js
- popd
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
notifications:
  irc:
    channels:
    - chat.freenode.net#jtransc
    on_success: never
    on_failure: always
  slack:
    rooms:
      secure: fDqxbvhCKZqXrl6oCcgsAUQQmjcUO3jaakR6pE3rY2GjUcwv7gFPA3VJNYBDe6EEq9nyYA4xJC+8IY/6OPm9kZh8/MLdosiJ7X2+FBo90Eo1hIpPAsJ8Vb5V1dY8jO7Luv2Drd+kwkwtNtLDxbdL3YOuAITYtKehQa1KRhkMuqIu4yFd5yApTzynsyBRypo0Hn4wTXCgB6s1Ch/TCuDDCAaHvPE5nXuJkhRvuZXI04EjpK/WIy2GK4VdYxojy+s6GMrhg++VjgzJuZvIbgkYb8ks5LmlCnK6DI96zSYes6L+ExWPVeUnMDMEH6M+9313I9d7nQBjO4z/Fk11W19KDQ6Z5CM7knm8n7mQ/CVF9vat1xo131ZvDYBzxT5zBzo6jaGYGE7CAdryfF/Gs3IUyWDKSJiBPa3FXhErVsg80sqQ+hK48a1hqh+RnsQ6wsH7y/cJBAQNf2c+Q/IFdpIIUu2a+iFEPTfco+U0DPfxQIaVjoGVIBCHE+E1jRTK0IeEqwxog03Cwcjq20FDhhnaiFYIRURjwDs+gWWpmBRDI1yi7+WAQzis0yoeapsan5/B9km2mEQqQnirL8zMNv4rJ/Ra6PgSmXs/GpYe1yjXa30SZSa4NKY/ySodYNZ3iMPSyocTrA0uC2d9/WhSZAIC9Av3VHg1Zh34sNBDX1S32w0=
    on_success: never
    on_failure: always
    on_start: never
#matrix:
#  include:
#    - os: linux
#      dist: trusty
#      sudo: required
#    #- os: osx
#    #  osx_image: xcode7.2